"""create workspace memberships

Revision ID: c1c967986e47
Revises: b675506a2764
Create Date: 2026-08-22 06:48:13.061234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1c967986e47'
down_revision: Union[str, Sequence[str], None] = 'b675506a2764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workspace_memberships',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('workspace_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_workspace_memberships_user_id'),
        'workspace_memberships',
        ['user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_workspace_memberships_workspace_id'),
        'workspace_memberships',
        ['workspace_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_workspace_memberships_workspace_id'),
        table_name='workspace_memberships',
    )
    op.drop_index(
        op.f('ix_workspace_memberships_user_id'),
        table_name='workspace_memberships',
    )
    op.drop_table('workspace_memberships')
    # ### end Alembic commands ###
